### ISSUE TITLE
RuboCop 0.80 surfaces which unconfigured new cops we have

### ISSUE THREAD

**Issue by issyl0** [alphagov/rubocop-govuk#16]
I noticed this on an app's Dependabot gem bump PR CI failure for `rubocop-govuk`.

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
```

This new informational messaging is a [feature](https://github.com/rubocop-hq/rubocop/issues/7731) which wasn't immediately obvious when dealing with #13 (I was looking for added and removed cops, but not much else).

We should make decisions about whether to include them and bump the gem version again.

**Comment by richardTowers** [comment]
👍  from me on including them.

I'm not volunteering to do the work though, and I think @issyl0's probably done enough rubocop for the week 😅
