### ISSUE TITLE
Latest release surfaces unconfigured new cops and wrong namespace

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/rubocop-govuk#35]
Hi team,

Dependabot kindly dropped a PR into one of my teams repos to bump this gem to v3.4.0. One inspected the terminal output I spotted the following warning messages are now being outputted.

```
/../ruby/2.6.5/lib/ruby/gems/2.6.0/gems/rubocop-govuk-3.4.0/config/other-lint.yml: Lint/EndBlock has the wrong namespace - should be Style
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
For more information: https://docs.rubocop.org/en/latest/versioning/
```

**Comment by issyl0** [comment]
Thanks, @aliuk2012. We had this with the last RuboCop release as well. We'll do some thinking on how to manage the seemingly continuous influx of new cops in a better way! 🤔
