### ISSUE TITLE
gem `rubocop-rails` support

### ISSUE THREAD

**Issue by likeuwill** [alphagov/rubocop-govuk#7]
Can you provide support `rubocop-rails`gem ?

**Comment by theseanything** [comment]
Hi @likeuwill, the gem already provides support `rubocop-rails` and include extra rules for Rails. You can enable them by inheriting `config/rails.yml` in your `.rubocop.yml`:
e.g.
```
# .rubocop.yml
inherit_gem:
  rubocop-govuk: 
    - config/rails.yml
```

**Comment by likeuwill** [comment]
Hi @theseanything.

Yes I know, but problem when I enable it I got more than 1000 offenses from ruby lint, e.g.
```
Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping
```
Of course I can disable it but in rubocop.yml, but i want to keep using `rubocop-rails` and their config.
Would be nice to be abble load config from `rubocop-rails` and `rubocop-govuk`

Thank you for your time, anyway ;)

P.S. Fast review, I don't see a reason to enable this rules in rails.yml:
Style/StringLiterals
Style/TrailingCommaInHashLiteral
Style/TrailingCommaInArguments

**Comment by theseanything** [comment]
Not sure I fully understand what you rules you would like enabled. 

If you want just the Ruby rules from `rubocop-govuk` and the rules from `rubocop-rails`,  your project's `.rubocop.yml` would look something like this:

```yml
# .rubocop.yml
inherit_gem:
  rubocop-govuk: 
    - config/default.yml

require: rubocop-rails
```

`rubocop-rails` should be available, as it is a dependency of `rubocop-govuk`. (But if you use it directly you should probably declare it in your Gemfile.)

**Comment by likeuwill** [comment]
Yes you right it's working both. I was surprised why it turned on `Style/StringLiterals`
My rubocop.yml
```
require: rubocop-rails
inherit_from: ./lib/rubocop/blacklist.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
```
Thank you. You can close this issue.
